src/Activities/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django_nyt.urls import get_pattern as get_nyt_pattern

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^cabinet/', include('cabinet.urls')),
    url(r'^chat/', include('chat.urls')),
    url(r'^', include('authentication.urls')),
    url(r'^', include('activity.urls')),
    url(r'^', include('myactivities.urls')),
    url(r'^subscriptions/', include('subscriptions.urls')),
    url(r'^notifications/', get_nyt_pattern()),
]

src/activity/urls.py
from django.conf.urls import url
from . import views
from . import statistics


app_name = 'activity'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^activity/search/$', views.ActivityList.as_view(), name='search'),
    # url(r'^activity/search/(?P<page>\d+)/$', views.ActivityList.as_view()),

    url(r'^activity/create/$', views.create, name='activity_create'),
    url(r'^activity/create/(?P<activity_id>\d+)$', views.create, name='activity_create'),
    url(r'^activity/(?P<activity_id>\d+)/$', views.detail, name='activity_detail'),
    url(r'^activity/edit/(?P<activity_id>\d+)/$', views.edit, name='activity_edit'),
    url(r'^activity/delete', views.delete, name='activity_delete'),
    url(r'^activity/(?P<activity_id>\d+)/dismiss/$', views.dismiss, name='dismiss_activity'),

    url(r'activity/hints/', views.get_hints, name='activity_hints'),

    url(r'activity/join', views.join, name='join_activity'),
    url(r'activity/recommendations$', statistics.recommendations, name='recommendations'),
    url(r'^activity/(?P<activity_id>\d+)/locations/$', views.locations, name='locations'),
    url(r'^activity/(?P<activity_id>\d+)/status/change/(?P<new_status>\S{2})/$', views.change_status, name='change_status'),
    url(r'^activity/(?P<activity_id>\d+)/rating/change/(?P<new_rating>\d+)/$', views.change_rating, name='change_rating'),
    url(r'^activity/(?P<activity_id>\d+)/participant/(?P<participant_id>\d+)/rating/change/(?P<new_rating>\d+)/$', views.change_participant_rating, name='change_participant_rating'),
    url(r'^activity/(?P<activity_id>\d+)/participant/(?P<participant_id>\d+)/comment/add/$', views.add_comment_for_participant, name='add_comment_for_participant'),

    url(r'^activity/(?P<activity_id>\d+)/comment/add/$', views.add_comment_for_activity, name='add_comment_for_activity'),

    url(r'^activity/(?P<activity_id>\d+)/participant/(?P<participant_id>\d+)/kick/$', views.kick_participant, name='kick_participant'),

]

src/authentication/urls.py
from django.conf.urls import url
from authentication import views
import django.contrib.auth.views

app_name = 'auth'

urlpatterns = [
    url(r'^login/', views.login, name='login'),
    url(r'^signup/', views.signup, name='signup'),
    url(r'^logout/', django.contrib.auth.views.logout, {'next_page':'/'}, name='logout'),
]

src/cabinet/urls.py
from django.conf.urls import url
from . import views


app_name = 'cabinet'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^user/(?P<user_id>\d+)/$', views.user_detail, name='user_detail'),
]

src/chat/urls.py
from django.conf.urls import url
from . import views


app_name = 'chat'
urlpatterns = [
    url(r'^', views.index, name="index"),
    # url(r'send/', views.send_Comment, name="send"),
       
]

src/django_nyt/urls.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import
from __future__ import unicode_literals

from django import VERSION as DJANGO_VERSION
from django.conf.urls import url, include

from . import views

app_name = 'nyt'

urlpatterns = [
    url('^json/get/$', views.get_notifications, name='json_get'),
    url('^json/get/(?P<latest_id>\d+)/$', views.get_notifications, name='json_get'),
    url('^json/mark-read/$', views.mark_read, name='json_mark_read_base'),
    url('^json/mark-read/(\d+)/$', views.mark_read, name='json_mark_read'),
    url('^json/mark-read/(?P<id_lte>\d+)/(?P<id_gte>\d+)/$', views.mark_read, name='json_mark_read'),
    url('^goto/(?P<notification_id>\d+)/$', views.goto, name='goto'),
    url('^goto/$', views.goto, name='goto_base'),
]


if DJANGO_VERSION < (1, 8):
    from django.conf.urls import patterns
    urlpatterns = patterns('', *urlpatterns)


def get_pattern(app_name=app_name, namespace="nyt"):
    """Every url resolution takes place as "nyt:view_name".
       https://docs.djangoproject.com/en/dev/topics/http/urls/#topics-http-reversing-url-namespaces
    """
    if DJANGO_VERSION < (1, 9):
        return urlpatterns, app_name, namespace
    else:
        return include('django_nyt.urls',)

src/myactivities/urls.py
from django.conf.urls import url
from myactivities import views
import django.contrib.auth.views

app_name = 'myactivities'

urlpatterns = [
    url(r'activities/created/$', views.created, name='created_activities'),
    url(r'activities/participated/$', views.participated, name='participated_activities')
]

src/templates/base.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Activity Planner</title>

    <!-- css -->
    <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
    <link href="{% static "font-awesome/css/font-awesome.min.css" %}" rel="stylesheet" type="text/css"/>
    <link href="{% static "css/nivo-lightbox.css" %}" rel="stylesheet"/>
    <link href="{% static "css/nivo-lightbox-theme/default/default.css" %}" rel="stylesheet" type="text/css"/>
    <link href="{% static "css/animations.css" %}" rel="stylesheet"/>
    <link href="{% static "css/style.css" %}" rel="stylesheet">
    <link href="{% static "color/default.css" %}" rel="stylesheet">


    <!-- CSS circle loader -->
    <link href="{% static "css/circle-loader.css" %}" rel="stylesheet">

    <!-- card & shadow -->
    <link href="{% static "css/card.css" %}" rel="stylesheet">

    <link href="{% static "css/bootstrap-vert-margin-shim.css" %}" rel="stylesheet">

    <!-- css typeahead widget -->
    <link href="{% static 'css/typeahead/typeahead.css' %}" rel="stylesheet">

    <!-- css amaran notifcation -->
    <link href="{% static 'css/amaran/amaran.min.css' %}" rel="stylesheet">


    <link rel="stylesheet" type="text/css" href="{% static 'css/datetimepicker/jquery.datetimepicker.css' %}"/>


    {% block head %}

    {% endblock %}
</head>

<body id="page-top" data-spy="scroll" data-target=".navbar-custom">

{% block header %}
{% endblock %}

<!-- Navigation -->
<div id="navigation">
    <nav class="navbar navbar-custom" role="navigation">
        <div class="container">
            <div class="row">
                <div class="col-md-2">
                    <div class="site-logo">
                        <a href="/" class="brand">APlanner</a>
                    </div>
                </div>


                <div class="col-md-10">

                    <!-- Brand and toggle get grouped for better mobile display -->
                    <div class="navbar-header">
                        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#menu">
                            <i class="fa fa-bars"></i>
                        </button>
                    </div>
                    <div class="collapse navbar-collapse" id="menu">
                        {% include "navigation.html" %}
                        {% block navbar %}{% endblock %}
                    </div>

                </div>
            </div>
        </div>
        <!-- /.container -->
    </nav>
</div>
<!-- /Navigation -->


<div class="page-wrap">
    {% block content %}
    {% endblock %}
</div>

<footer>
    <div class="container">
        <div class="row">
            <div class="col-md-6">
                <ul class="footer-menu">
                    <li><a href="/">Home</a></li>
                </ul>
            </div>
            <div class="col-md-6 text-right">
                foooter
            </div>
        </div>
    </div>
</footer>

<!-- Core JavaScript Files -->
<script src="{% static "js/jquery.min.js" %}"></script>
<script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
<script src="{% static "js/jquery.sticky.js" %}"></script>
<script src="{% static "js/jquery.easing.min.js" %}"></script>
<script src="{% static "js/jquery.scrollTo.js" %}"></script>
<script src="{% static "js/jquery.appear.js" %}"></script>
<script src="{% static "js/stellar.js" %}"></script>
<script src="{% static "js/nivo-lightbox.min.js" %}"></script>

<script src="{% static "js/custom.js" %}"></script>
<script src="{% static "js/css3-animate-it.js" %}"></script>

<script src="{% static "js/typeahead/typeahead.bundle.min.js" %}"></script>
<script src="{% static "js/amaran/jquery.amaran.min.js" %}"></script>


<script src="{% static 'js/datetimepicker/jquery.datetimepicker.full.min.js' %}"></script>

<!-- custom page scripts. widgets and etc -->
{% block scripts %}
{% endblock %}


<script type="text/javascript">
    var URL_NYT_GET_NEW = "{% url "nyt:json_get" %}";
    var URL_NYT_MARK_READ = "{% url "nyt:json_mark_read_base" %}";
    var URL_NYT_GOTO = "{% url "nyt:goto_base" %}";

    var nyt_oldest_id = 0;
    var nyt_latest_id = 0;
    var nyt_update_timeout = 30000;
    var nyt_update_timeout_adjust = 1.2; // factor to adjust between each timeout.


    function ajaxError() {
    }

    $.ajaxSetup({
        timeout: 7000,
        cache: false,
        error: function (e, xhr, settings, exception) {
            ajaxError();
        }
    });

    function jsonWrapper(url, callback) {
        $.getJSON(url, function (data) {
            if (data == null) {
                ajaxError();
            } else {
                callback(data);
            }
        });
    }

    function nyt_update() {
        jsonWrapper(URL_NYT_GET_NEW + nyt_latest_id + '/', function (data) {
            if (data.success) {
                if (data.objects.length > 0) {
                    $.amaran({
                        'message': data.objects[0]["message"],
                        'position': 'bottom right'
                    });
                }
            }
        });
    }

    // Mark all <li> items read and tell the server.
    function nyt_mark_read() {
        $('.notification-li').remove();
        var url = URL_NYT_MARK_READ + nyt_latest_id + '/' + nyt_oldest_id + '/';
        nyt_oldest_id = 0;
        nyt_latest_id = 0;
        jsonWrapper(url, function (data) {
            if (data.success) {
                $('.notifications-empty').show();
                nyt_update();
            }
        });
    }

    // Call this function to use traditional polling
    function update_timeout() {
        setTimeout("nyt_update()", nyt_update_timeout);
        setTimeout("update_timeout()", nyt_update_timeout);
        nyt_update_timeout *= nyt_update_timeout_adjust;
    }

    // Don't check immediately... some users just click through pages very quickly.
    //setTimeout("nyt_update()", 2000);

    var socket = new WebSocket('ws://' + window.location.host + "/nyt/?session_key={{ request.session.session_key }}");

    $(document).ready(function () {
        // update_timeout();
        socket.onopen = function () {
            //console.log("Sending hello world");
            //socket.send("hello world");
        }
        socket.onmessage = function (e) {
            console.log("Got some message, so going to update");
            nyt_update();
        }

        if (socket.readyState == WebSocket.OPEN) socket.onopen();
    });

</script>

</body>
</html>

src/templates/navigation.html
<ul class="nav navbar-nav navbar-right">
    {% if user.is_authenticated %}
        <li><a href="{% url 'activity:activity_create' %}">Create</a></li>
        <li><a href="{% url 'myactivities:created_activities' %}">Created</a></li>
        <li><a href="{% url 'myactivities:participated_activities' %}">Participated</a></li>
        <li><a href="{% url 'cabinet:index' %}">Cabinet</a></li>
        <li><a href="{% url 'auth:logout' %}">Logout</a></li>
    {% else %}
        <li><a href="{% url 'auth:login' %}">Login</a></li>
        <li><a href="{% url 'auth:signup' %}">Sign up</a></li>
    {% endif %}
</ul>