src/Activities/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django_nyt.urls import get_pattern as get_nyt_pattern

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^cabinet/', include('cabinet.urls')),
    url(r'^chat/', include('chat.urls')),
    url(r'^', include('authentication.urls')),
    url(r'^', include('activity.urls')),
    url(r'^', include('myactivities.urls')),
    url(r'^subscriptions/', include('subscriptions.urls')),
    url(r'^notifications/', get_nyt_pattern()),
]

src/activity/urls.py
from django.conf.urls import url
from . import views
from . import statistics


app_name = 'activity'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^activity/search/$', views.ActivityList.as_view(), name='search'),
    # url(r'^activity/search/(?P<page>\d+)/$', views.ActivityList.as_view()),

    url(r'^activity/create/$', views.create, name='activity_create'),
    url(r'^activity/create/(?P<activity_id>\d+)$', views.create, name='activity_create'),
    url(r'^activity/(?P<activity_id>\d+)/$', views.detail, name='activity_detail'),
    url(r'^activity/edit/(?P<activity_id>\d+)/$', views.edit, name='activity_edit'),
    url(r'^activity/delete', views.delete, name='activity_delete'),
    url(r'^activity/(?P<activity_id>\d+)/dismiss/$', views.dismiss, name='dismiss_activity'),

    url(r'activity/hints/', views.get_hints, name='activity_hints'),

    url(r'activity/join', views.join, name='join_activity'),
    url(r'activity/recommendations$', statistics.recommendations, name='recommendations'),
    url(r'^activity/(?P<activity_id>\d+)/locations/$', views.locations, name='locations'),
    url(r'^activity/(?P<activity_id>\d+)/status/change/(?P<new_status>\S{2})/$', views.change_status, name='change_status'),
    url(r'^activity/(?P<activity_id>\d+)/rating/change/(?P<new_rating>\d+)/$', views.change_rating, name='change_rating'),
    url(r'^activity/(?P<activity_id>\d+)/participant/(?P<participant_id>\d+)/rating/change/(?P<new_rating>\d+)/$', views.change_participant_rating, name='change_participant_rating'),
    url(r'^activity/(?P<activity_id>\d+)/participant/(?P<participant_id>\d+)/comment/add/$', views.add_comment_for_participant, name='add_comment_for_participant'),

    url(r'^activity/(?P<activity_id>\d+)/comment/add/$', views.add_comment_for_activity, name='add_comment_for_activity'),

    url(r'^activity/(?P<activity_id>\d+)/participant/(?P<participant_id>\d+)/kick/$', views.kick_participant, name='kick_participant'),

]

src/chat/urls.py
from django.conf.urls import url
from . import views


app_name = 'chat'
urlpatterns = [
    url(r'^', views.index, name="index"),
    # url(r'send/', views.send_Comment, name="send"),
       
]

src/django_nyt/urls.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import
from __future__ import unicode_literals

from django import VERSION as DJANGO_VERSION
from django.conf.urls import url, include

from . import views

app_name = 'nyt'

urlpatterns = [
    url('^json/get/$', views.get_notifications, name='json_get'),
    url('^json/get/(?P<latest_id>\d+)/$', views.get_notifications, name='json_get'),
    url('^json/mark-read/$', views.mark_read, name='json_mark_read_base'),
    url('^json/mark-read/(\d+)/$', views.mark_read, name='json_mark_read'),
    url('^json/mark-read/(?P<id_lte>\d+)/(?P<id_gte>\d+)/$', views.mark_read, name='json_mark_read'),
    url('^goto/(?P<notification_id>\d+)/$', views.goto, name='goto'),
    url('^goto/$', views.goto, name='goto_base'),
]


if DJANGO_VERSION < (1, 8):
    from django.conf.urls import patterns
    urlpatterns = patterns('', *urlpatterns)


def get_pattern(app_name=app_name, namespace="nyt"):
    """Every url resolution takes place as "nyt:view_name".
       https://docs.djangoproject.com/en/dev/topics/http/urls/#topics-http-reversing-url-namespaces
    """
    if DJANGO_VERSION < (1, 9):
        return urlpatterns, app_name, namespace
    else:
        return include('django_nyt.urls',)

src/myactivities/urls.py
from django.conf.urls import url
from myactivities import views
import django.contrib.auth.views

app_name = 'myactivities'

urlpatterns = [
    url(r'activities/created/$', views.created, name='created_activities'),
    url(r'activities/participated/$', views.participated, name='participated_activities')
]

src/activity/models.py
import json

from django.contrib.auth.models import User
from django.db import models
from locations.models import Location
from django.apps import apps
from django.db.models import Q
from django.contrib.postgres.search import TrigramSimilarity
from django_nyt.utils import notify, subscribe
from django.db.models import Avg

# Create your models here.
class ActivityCategory(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name


class ActivityType(models.Model):
    name = models.CharField(max_length=50)
    category = models.ForeignKey('ActivityCategory', on_delete=models.CASCADE)

    def __str__(self):
        return self.name


class Activity(models.Model):
    SCHEDULED = 'SC'
    CANCELED = 'CN'
    PERFORMED = 'PF'
    STATUSES = (
        (SCHEDULED, 'Scheduled'),
        (CANCELED, 'Canceled'),
        (PERFORMED, 'Performed'),
    )

    name = models.CharField(max_length=30)
    description = models.CharField(max_length=250)
    start_time = models.DateTimeField()
    end_time = models.DateTimeField()
    status = models.CharField(
        max_length=2,
        choices=STATUSES,
        default=SCHEDULED,
    )
    requirements = models.TextField()
    comments = models.ManyToManyField(User, through='Comment')
    participants = models.ManyToManyField(User, through='Participant',
                                          related_name='participants_of_activity')
    participants_limit = models.PositiveIntegerField()
    locations = models.ManyToManyField(Location, through='ActivityLocation')
    organizer = models.ForeignKey(User, on_delete=models.SET_NULL, null=True,
                                  related_name='organizer_of_activity')
    activity_category = models.ForeignKey(ActivityCategory, on_delete=models.SET_NULL, null=True)
    activity_type = models.ForeignKey(ActivityType, on_delete=models.SET_NULL, null=True)

    def __str__(self):
        return self.name

    def rating(self):
        """ This method return the average rating of the activity
         which was given by its participants. """
        result = 0
        n = 0
        try:
            for participant in self.participant_set.all():
                if participant.rating is not None:
                    result += participant.rating
                    n += 1
        except Exception as e:
            print(e)
        if n > 0:
            return round(result / n)
        return None

    def notify_subscribers(self):
        SearchFilter = apps.get_model('subscriptions','SearchFilter')
        Subscription = apps.get_model('subscriptions', 'Subscription')

        filters = SearchFilter.objects.annotate(
            similarity=TrigramSimilarity('search', self.name)
        ).filter(Q(activity_type = self.activity_type) | Q(activity_category = self.activity_category) | Q(similarity__gt=0.1))

        for f in filters:
            subscribers = Subscription.objects.filter(search_filter = f)
            for s in subscribers:
                if s.user != self.organizer:
                    notify(
                        ("New suitable activity %s" % self.name),
                        "test",
                        target_object=s.user,
                    )

        return
        

class ActivityLocation(models.Model):
    location = models.ForeignKey(Location, on_delete=models.CASCADE)
    activity = models.ForeignKey(Activity, on_delete=models.CASCADE)
    index = models.PositiveSmallIntegerField()

    def to_json(self):
        return dict(index=self.index, location=self.location.to_json())  # , activity=self.activity.to_json()

    @staticmethod
    def from_json(json_str):
        """ Create object from JSON """
        data = json.loads(json_str)['locations']
        # create objects
        objs = []
        index = 0
        for val in data:
            act_loc = ActivityLocation()
            act_loc.index = index
            index += 1
            location = Location.from_dict(val)
            act_loc.location = location
            objs.append(act_loc)
        return objs


class Participant(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    activity = models.ForeignKey(Activity, on_delete=models.CASCADE)
    rating = models.PositiveSmallIntegerField(null=True)
    comment = models.TextField()
    participant_rating = models.PositiveSmallIntegerField(null=True)
    comment_for_participant = models.TextField()

    @property
    def total_rating(self):
        rating = Participant.objects.filter(user=self.user).aggregate(Avg('participant_rating'))

        return rating['participant_rating__avg']


# perhaps we should move 'Comments' to its own app later
class Comment(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    activity = models.ForeignKey(Activity, on_delete=models.CASCADE)
    comment = models.TextField()

src/activity/forms.py
from django import forms
from django.core.exceptions import ValidationError
from activity.models import Activity
from django.utils.timezone import utc
import datetime
from bootstrap3_datetime.widgets import DateTimePicker


class ActivityForm(forms.ModelForm):
    title = 'Create a new activity'
    id = forms.IntegerField(widget=forms.HiddenInput, required=False)

    class Meta:
        model = Activity
        fields = ['id', 'name', 'description', 'requirements', 'start_time', 'end_time', 'participants_limit',
                  'activity_category', 'activity_type']
        error_messages = {'required': 'This field is required'}
        widgets = {
            'start_time': DateTimePicker(options={"format": "YYYY-MM-DD HH:mm"}),
            'end_time': DateTimePicker(options={"format": "YYYY-MM-DD HH:mm"})
        }

    def clean(self):
        start_time = self.cleaned_data.get('start_time')
        if start_time is None:
            start_time = datetime.datetime.utcnow().replace(tzinfo=utc)
            return self.cleaned_data
        if start_time <= datetime.datetime.utcnow().replace(tzinfo=utc):
            raise ValidationError("You can't choose past time, please choose correct one.")
        if start_time > self.cleaned_data.get('end_time'):
            raise ValidationError("Activity can't end before starting, please choose correct dates.")
        if self.cleaned_data.get('participants_limit') <= 0:
            raise ValidationError("At least one participant is required.")
        return self.cleaned_data

    def __init__(self, *args, **kwargs):
        super(ActivityForm, self).__init__(*args, **kwargs)
        for field in iter(self.fields):
            self.fields[field].widget.attrs.update({
                'class': 'form-control'
            })
        self.fields['name'].widget.attrs['placeholder'] = 'title'
        self.fields['name'].widget.attrs['onChange'] = '{recommendationsRequest();}'
        self.fields['description'].widget.attrs['placeholder'] = 'description'
        self.fields['description'].widget.attrs['onChange'] = '{recommendationsRequest();}'
        self.fields['requirements'].widget.attrs['placeholder'] = 'requirements'
        self.fields['requirements'].widget.attrs['onChange'] = '{recommendationsRequest();}'
        self.fields['participants_limit'].widget.attrs['placeholder'] = 'required participants (not counting yourself)'
        self.fields['participants_limit'].widget.attrs['onChange'] = '{recommendationsRequest();}'
        self.fields['activity_type'].widget.attrs['id'] = 'create_form_activity_type'
        self.fields['activity_type'].widget.attrs['onChange'] = '{recommendationsRequest();}'
        self.fields['start_time'].widget.attrs['onChange'] = '{recommendationsRequest();}'
        self.fields['end_time'].widget.attrs['onChange'] = '{recommendationsRequest();}'
        #self.fields['locations'].widget.attrs['onChange'] = '{recommendationsRequest();}'

src/activity/templates/activity/activities_reccomendation.html
{% block content %}
{% if time_from_rec and time_to_rec %}
<div class="panel panel-success">
  <div class="panel-heading">
    <h3 class="panel-title">Time recommendations</h3>
  </div>
  <div class="panel-body">
  	This activity usually take place between {{ time_from_rec }} and {{ time_to_rec }}.
  </div>
</div>
{% endif %}
{% if activities %}
<div class="panel panel-success">
  <!-- Default panel contents -->
  <div class="panel-heading">Similar activities</div>
  <!-- List group -->
  <ul class="list-group">
  {% for activity in activities %}
  <li class="list-group-item">
	  <div class="row">
	  	<div class="col-xs-6 col-md-3">
	  		{{ activity.name }}
	  	</div>
	  	<div class="col-xs-6 col-md-3">
	  		{{ activity.description }}
	  	</div>
	  	<div class="col-xs-6 col-md-3">
	  		{{ activity.start_time }}
	  	</div>
	  	<div class="col-xs-6 col-md-3">
		  	<button type="button" class="btn btn-skin"
		    onclick="$.ajax('/activity/join?user_id={{ user.id }}&activity_id={{ activity.id }}')
		    .done(function() { window.location ='{% url 'myactivities:participated_activities' %}'; })">
		    Join
		    </button>	
	  	</div>
	  </div>
  </li>
  {% endfor %}
  </ul>
</div>
{% endif %}
{% endblock %}

src/activity/templates/activity/create.html
{% extends 'base.html' %}
{% load leaflet_tags %}
{% load staticfiles %}
{% block head %}
    {% leaflet_js %}
    {% leaflet_css %}

    <!-- Optional theme -->
    <link rel="stylesheet" href="{% static "css/bootstrap.min.css" %}" media="screen">
    <link rel="stylesheet" href="{% static "css/bootstrap-datetimepicker.min.css" %}" media="screen"/>
    <script src="{% static "js/jquery-1.9.1.js" %}"></script>
    <script src="{% static "js/jquery.min.js" %}"></script>
    {{ activity_form.media }}
{% endblock %}

{% block content %}


    <section class="home-section nopadd-bot color-dark text-center">

        <div class="container marginbot-20 formCreate">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2">
                    <div class="animatedParent">
                        <div class="section-heading text-center">
                            <h2 class="h-bold animated bounceInDown">{{ activity_form.title }}</h2>
                            <div class="divider-header"></div>
                        </div>
                    </div>
                </div>
            </div>

        </div>
        <div>Save your time! Create a new activity based on your previous ones!</div>

        <div class="container">
            <div class="row marginbot-80">
                <div class="col-md-8 col-md-offset-2">
                    <div class="col-md-12">
                        <div class="row marginbot-30">
                            <div class="btn-group">
                                <div class="dropdown">
                                    <button type="button" class="btn btn-skin dropdown-toggle" data-toggle="dropdown" id="#textDropDown">
                                    </button>
                                    <ul class="dropdown-menu pre-scrollable" role="menu">
                                        {% for activity in activities %}
                                            <li>
                                                <a href="{% url 'activity:activity_create' activity.id %}">{{ activity.name }}</a>
                                            </li>
                                        {% endfor %}
                                    </ul>
                                </div>
                            </div>
                        </div>

                    </div>
                    <form id="activityForm" class="form-horizontal" action="" method="POST">
                        {% csrf_token %}
                        {% for error in activity_form.non_field_errors %}
                            <div class="alert alert-danger">{{ error }}</div>
                        {% endfor %}
                        <div class="row">
                            <div class="form-group">
                                <div class="col-md-12">{{ activity_form.name }}</div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="form-group">
                                <div class="col-md-12">{{ activity_form.description }}</div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="form-group">
                                <div class="col-md-12">{{ activity_form.requirements }}</div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="form-group">
                                <div class="col-md-6">
                                    <label for="{{ activity_form.start_time.id_for_label }}"
                                           class="col-md-2 control-label">From:</label>
                                    <div class="col-md-10">{{ activity_form.start_time }}</div>
                                </div>
                                <div class="col-md-6">
                                    <label for="{{ activity_form.end_time.id_for_label }}"
                                           class="col-md-2 control-label">To:</label>
                                    <div class="col-md-10">{{ activity_form.end_time }}</div>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="form-group">
                                <div class="col-md-12">{{ activity_form.participants_limit }}</div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="form-group">
                                <div class="col-md-12">{{ activity_form.locations }}</div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="form-group">
                                <div class="col-md-6">
                                    <label for="{{ activity_form.activity_category.id_for_label }}"
                                           class="col-md-4 control-label">Category:</label>
                                    <div class="col-md-8">{{ activity_form.activity_category }}</div>
                                </div>
                                <div class="col-md-6">
                                    <label for="{{ activity_form.activity_type.id_for_label }}"
                                           class="col-md-4 control-label">Type:</label>
                                    <div class="col-md-8">{{ activity_form.activity_type }}</div>
                                </div>
                            </div>
                        </div>
                        <div class="row map">
                            {% leaflet_map "activity_map" %}
                        </div>
                        <input type="submit" value="Create" class="btn btn-skin btn-lg btn-block"/>
                    </form>

                </div>
            </div>
        </div>

        <div class="container marginbot-50">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2">
                    <div class="animatedParent">
                        <div id="div_reccomendation" class="section-heading text-center">
                        </div>
                    </div>
                </div>
            </div>
        </div>

    </section>

{% endblock %}

{% block scripts %}

    <!--<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/js/bootstrap.min.js"></script>-->
    <script type="text/javascript" src="{% static "js/moment.js" %}"></script>
    <script type="text/javascript" src="{% static "js/bootstrap-datetimepicker.min.js" %}" charset="UTF-8"></script>

    <script type="text/javascript">
        function recommendationsRequest() {
            var type = $('#create_form_activity_type').val();

            if (type == '') {
                document.getElementById("div_reccomendation").innerHTML = "";
                return;
            }

            $.ajax({
                url: "{% url 'activity:recommendations' %}" + '?' + 'type=' + type,
                type: "GET",
                contentType: "application/text",
                async: true,
                success: recommendationsResponse,
                error: recommendationsError,
            })
        }
        ;

        function recommendationsResponse(response) {
            document.getElementById("div_reccomendation").innerHTML = response;
        }
        ;

        function recommendationsError(response) {
            document.getElementById("div_reccomendation").innerHTML = "";
        }
        ;
    </script>


    <script type="text/javascript">
        var layers = {};

        function onMarkerClick(e) {
            // get the marker on which click event fired
            var marker = e.target;
            // remove it from the map
            if (layers.hasLayer(marker)) {
                console.log(marker);
                layers.removeLayer(marker);
            }
        }

        // adds marker and its description (if any) to the specified map
        function addMarker(map, loc) {
            var marker = L.marker([loc.latitude, loc.longitude], {draggable: true});
            marker.on('click', onMarkerClick);
            // add a marker to the map
            layers.addLayer(marker);
            // add popup for the marker if it has any name
            if (loc.name) {
                var popup = L.popup()
                        .setLatLng([loc.latitude, loc.longitude])
                        .setContent(loc.name);
                marker.bindPopup(popup);
            }
        }

        // create location object from the given parameters
        function createLocation(latlng, name) {
            var loc = {};
            loc.latitude = latlng.lat;
            loc.longitude = latlng.lng;
            loc.name = name;
            return loc;
        }

        function onMapClick(e) {
            // if there is location information, then add new marker on the map
            if (e.latlng) {
                var loc = createLocation(e.latlng, '');
                addMarker(e.target, loc);
            }
        }

        $(window).on('map:init', function (e) {
            var detail = e.originalEvent ? e.originalEvent.detail : e.detail;
            layers = L.layerGroup().addTo(detail.map);
            detail.map.on('click', onMapClick);
            detail.map.locate();

            // add geo information to the post request before submit
            $('#activityForm').submit(function () { //listen for submit event
                var res = [];
                // pack all locations into json array...
                layers.eachLayer(function (layer) {
                    var latlng = layer.getLatLng();
                    var loc = createLocation(latlng, '');
                    res.push(JSON.stringify(loc));
                });
                // ...and attach it to the current form
                $('<input />').attr('type', 'hidden')
                        .attr('name', 'locations')
                        .attr('value', '{ "locations": [' + res + ']}')
                        .appendTo('#activityForm');
                return true;
            });
        });


        $(document).ready(function() {
            var name = $("#id_name").val();

            if (name.length == 0) {
                document.getElementById("#textDropDown").innerHTML = "Choose your activity..."+'<span class="caret"></span>';
            } else {
                document.getElementById("#textDropDown").innerHTML=name+'<span class="caret"></span>';
            }

            $('.datepicker').datetimepicker();

        });

    </script>
{% endblock %}