src/Activities/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django_nyt.urls import get_pattern as get_nyt_pattern

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^cabinet/', include('cabinet.urls')),
    url(r'^chat/', include('chat.urls')),
    url(r'^', include('authentication.urls')),
    url(r'^', include('activity.urls')),
    url(r'^', include('myactivities.urls')),
    url(r'^subscriptions/', include('subscriptions.urls')),
    url(r'^notifications/', get_nyt_pattern()),
]

src/cabinet/urls.py
from django.conf.urls import url
from . import views


app_name = 'cabinet'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^user/(?P<user_id>\d+)/$', views.user_detail, name='user_detail'),
]

src/chat/urls.py
from django.conf.urls import url
from . import views


app_name = 'chat'
urlpatterns = [
    url(r'^', views.index, name="index"),
    # url(r'send/', views.send_Comment, name="send"),
       
]

src/django_nyt/urls.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import
from __future__ import unicode_literals

from django import VERSION as DJANGO_VERSION
from django.conf.urls import url, include

from . import views

app_name = 'nyt'

urlpatterns = [
    url('^json/get/$', views.get_notifications, name='json_get'),
    url('^json/get/(?P<latest_id>\d+)/$', views.get_notifications, name='json_get'),
    url('^json/mark-read/$', views.mark_read, name='json_mark_read_base'),
    url('^json/mark-read/(\d+)/$', views.mark_read, name='json_mark_read'),
    url('^json/mark-read/(?P<id_lte>\d+)/(?P<id_gte>\d+)/$', views.mark_read, name='json_mark_read'),
    url('^goto/(?P<notification_id>\d+)/$', views.goto, name='goto'),
    url('^goto/$', views.goto, name='goto_base'),
]


if DJANGO_VERSION < (1, 8):
    from django.conf.urls import patterns
    urlpatterns = patterns('', *urlpatterns)


def get_pattern(app_name=app_name, namespace="nyt"):
    """Every url resolution takes place as "nyt:view_name".
       https://docs.djangoproject.com/en/dev/topics/http/urls/#topics-http-reversing-url-namespaces
    """
    if DJANGO_VERSION < (1, 9):
        return urlpatterns, app_name, namespace
    else:
        return include('django_nyt.urls',)

src/cabinet/models.py
from django.db import models

# Create your models here.

src/cabinet/forms.py
import re
from django import forms
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError


def validator_email(value):
    """ Email validator. Throws an exception in case if not valid email was provided. """
    if not re.match(r'^[^@]+@[^@]+\.[^@]+$', value):
        raise ValidationError('Incorrect Email')


def validate_phone(phone):
    if not re.match(r'^[0-9]{11}$', phone):
        raise ValidationError('Incorrect Phone')


def validate_telegram(telegram):
    if not re.match(r'^\@{1}[a-z,A-Z,0-9,_]*$', telegram):
        raise ValidationError('Incorrect Telegram')


def validate_date(date):
    if not re.match(r'^[0-9]{4}\-[0-9]{2}\-[0-9]{2}$', date):
        raise ValidationError('Incorrect Date. It should be in format YYYY-MM-DD')


def validate_gender(gender):
    if not (gender == 'F' or gender == 'M'):
        raise ValidationError('Incorrect Gender')


class UserSettingsForm(forms.Form):
    MALE = 'M'
    FEMALE = 'F'
    GENDER = ((MALE, 'Male'), (FEMALE, 'Female'))

    title = 'User profile'
    first_name = forms.CharField(label='First name', max_length=30, required=False,
                                 widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'First name'}))
    last_name = forms.CharField(label='Last name', max_length=30, required=False,
                                widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Last name'}))
    email = forms.EmailField(label='Email', max_length=254, required=False, validators=[validator_email],
                             widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Email'}))
    phone = forms.CharField(label='Phone', max_length=11, required=False, validators=[validate_phone],
                            widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Phone'}))
    telegram = forms.CharField(label='Telegram', max_length=30, required=False, validators=[validate_telegram],
                               widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Telegram'}))
    birth_date = forms.CharField(label='Birth date', max_length=10, required=False, validators=[validate_date],
                                 widget=forms.TextInput(attrs={'class': 'form-control span2', 'placeholder': 'Birth date'}))
    gender = forms.ChoiceField(choices=GENDER, required=False,
                               widget=forms.Select(attrs={'class': 'form-control', 'placeholder': 'Gender'}))

    class Meta:
        fields = ['first_name', 'last_name', 'email', 'phone', 'telegram', 'birth_date', 'gender']

src/cabinet/views.py
from django.contrib.auth.models import User
from django.shortcuts import render
from django.template import loader
from django.http import HttpResponse, HttpResponseRedirect
from activity.models import Activity, Participant
from authentication.models import User as MUser
from .forms import UserSettingsForm
from django.views.generic.edit import FormView
from django.core.exceptions import ObjectDoesNotExist


def index(request):
    if not request.user.is_authenticated():
        return HttpResponseRedirect('/login')
    user = request.user
    template = loader.get_template('cabinet.htm')
    # If the 'Profile' page was requested
    if request.method == 'GET':
        data = MUser.objects.get_or_create(user=user)[0]
        form = UserSettingsForm(initial={
            'first_name': '' if user.first_name is None else user.first_name,
            'last_name': '' if user.last_name is None else user.last_name,
            'email': '' if user.email is None else user.email,
            'phone': '' if data.phone is None else data.phone,
            'telegram': '' if data.telegram is None else data.telegram,
            'birth_date': '' if data.birth_date is None else data.birth_date.isoformat(),
            'gender': '' if data.gender is None else data.gender
        })
        return HttpResponse(template.render({'settings_form': form}, request))

    if request.method == 'POST':
        form = UserSettingsForm(data=request.POST)
        if form.is_valid():
            try:
                User.objects.filter(pk=user.pk).update(
                    first_name=None if form.cleaned_data['first_name'] == '' else form.cleaned_data['first_name'],
                    last_name=None if form.cleaned_data['last_name'] == '' else form.cleaned_data['last_name'],
                    email=None if form.cleaned_data['email'] == '' else form.cleaned_data['email'])
                MUser.objects.filter(pk=MUser.objects.get(user=user).pk).update(
                    phone=None if form.cleaned_data['phone'] == '' else form.cleaned_data['phone'],
                    telegram=None if form.cleaned_data['telegram'] == '' else form.cleaned_data['telegram'],
                    birth_date=None if form.cleaned_data['birth_date'] == '' else form.cleaned_data['birth_date'],
                    gender=None if form.cleaned_data['gender'] == '' else form.cleaned_data['gender'])
                return HttpResponseRedirect('/cabinet')
            except Exception as e:
                print(e)
    # return 400
    return HttpResponse(template.render({'settings_form': form}, request))

def user_detail(request, user_id):
    if not request.user.is_authenticated():
        return HttpResponseRedirect('/login')
    try:
        user = User.objects.get(id = user_id)
        user_info = MUser.objects.get_or_create(user = user)
        participated = Activity.objects.filter(participants = user)
        organized = Activity.objects.filter(organizer = user)
    except MUser.DoesNotExist:
        raise Http404("The user your are looking for doesn't exist.")
    return render(request, 'user_detail.html', {'user_info': user_info, 'user': user, 'participated': participated, 'organized': organized})

src/cabinet/templates/cabinet.htm
{% extends "base.html" %}
{% load static %}

{% block head %}
    <link href="{% static "css/datepicker.css" %}" rel="stylesheet">
{% endblock %}
{% block title %}Cabinet{% endblock %}
{% block content %}
    <section class="home-section nopadd-bot color-dark text-center">
        <div class="container marginbot-50">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2">
                    <div class="animatedParent">
                        <div class="section-heading text-center">
                            <h2 class="h-bold animated bounceInDown">{{ settings_form.title }}</h2>
                            <div class="divider-header"></div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="container">
            <div class="row marginbot-80">
                <div class="col-md-8 col-md-offset-2">
                    <form class="input-form form-horizontal" action="/cabinet/" method="post">
                        {% csrf_token %}
                        {% for field in settings_form %}
                            <div class="form-group form-group-lg">
                                <label class="col-sm-2 control-label"
                                       for="{{ field.html_name }}">{{ field.label }}</label>
                                <div class="col-sm-10">
                                    {% if field.name == 'birth_date' %}
                                        <div class="input-append date" data-date="{{ field.value }}"
                                             data-date-format="yyyy-mm-dd">
                                            {{ field }}
                                            <span class="add-on"><i class="icon-th"></i></span>
                                        </div>
                                    {% else %}
                                        {{ field }}
                                    {% endif %}
                                    {% if field.errors %}
                                        <li class="error-list">
                                            {% for error in field.errors %}
                                                <ul>{{ error }}</ul>
                                            {% endfor %}
                                        </li>
                                    {% endif %}
                                </div>
                            </div>
                        {% endfor %}
                        <input type="submit" value="Save" class="btn btn-skin btn-lg btn-block"/>
                    </form>
                </div>
            </div>
        </div>
    </section>
{% endblock %}
{% block scripts %}
    <script type="text/javascript" src="{% static "js/bootstrap-datepicker.js" %}"></script>
    <script type="text/javascript">
        $(function () {
            $('#id_birth_date').datepicker({
                format: 'yyyy-mm-dd'
            });
        });
    </script>
{% endblock %}

src/cabinet/templates/user_detail.html
{% extends "base.html" %}
{% load static %}

{% block head %}
    <style>
.pre-scrollable.activity {
  max-height: 100px !important;
  overflow-y: scroll;
}
    </style>

{% endblock %}

{% block content %}
 <section class="home-section nopadd-bot color-dark text-center">
        <div class="container marginbot-50">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2">
                    <div class="animatedParent">
                        <div class="section-heading text-center">
                            <h2 class="h-bold animated bounceInDown">User details</h2>
                            <div class="divider-header"></div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="container">
            <div class="row marginbot-80">
                <div class="col-md-8">
                        {% csrf_token %}
                            <div class="form-group form-group-lg">
                                <div class = "row ">
                                    <label class="col-sm-6 control-label text-right">User name:</label>
                                    <div class="col-sm-6 text-left">{{ user.last_name }} {{ user.first_name }}</div>
                                </div>
                                <div class = "row ">
                                    <label class="col-sm-6 control-label text-right">E-mail:</label>
                                    <div class="col-sm-6 text-left">{{ user_info.email }}</div>
                                </div>
                                <div class = "row">
                                    <label class="col-sm-6 control-label text-right">Phone:</label>
                                    <div class="col-sm-6 text-left">{{ user_info.phone }}</div>
                                </div>
                                <div class = "row">
                                    <label class="col-sm-6 control-label text-right">Telegram:</label>
                                    <div class="col-sm-6 text-left">{{ user_info.telegram }}</div>
                                </div>
                                <div class = "row">
                                    <label class="col-sm-6 control-label text-right">Date of birth:</label>
                                    <div class="col-sm-6 text-left">{{ user_info.birth_date }}</div>
                                </div>
                                <div class = "row">
                                    <label class="col-sm-6 control-label text-right">Gender:</label>
                                    <div class="col-sm-6 text-left">{{ user_info.gender }}</div>
                                </div>
                            </div>
                </div>
                <div class="col-md-4">
                    <div class = "row"><label class="col-sm-6 control-label text-left">Participated activities:</label></div>
                    <div class = "pre-scrollable activity">
                        {% if participated != 0 %}
                                    {% for participated_activity in participated %}
                                    <div>{{participated_activity.name}}</div>
                                    <hr>
                                    {% endfor %}
                        {% else %}
                            There is no participated activity yet!
                        {% endif %}
                    </div>
                
                    <div class = "row "><label class="col-sm-6 control-label">Organized activities:</label></div>
                    <div class = "pre-scrollable activity">
                        {% if organized != 0 %}
                            {% for organized_activity in organized %}
                                <div>{{organized_activity.name}}</div>
                                <!-- <div class="col-sm-6">{{organized_activity.name}}</div> -->
                                <hr>
                            {% endfor %}
                        {% else %}
                            There is no organized activity yet!
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
    </section>
{% endblock %}